import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import Nav from "@/components/Nav";
import doctorsDummyData from "/data/doctorsDummyData.json";
import specialistsDummy from "/data/specialistsDummyData.json";

const specialistsArray = specialistsDummy.specialists;

export default function Category({ specialist }) {
  const doctorsArray = doctorsDummyData.doctors;

  return (
    <>
      <Head>
        <title>{specialist.type} | NEXTGEN Doctors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen bg-[#F8FFFE] flex justify-center">
        <div className="flex flex-col w-[95%] max-w-[900px] h-screen pt-5 pb-14 xl:pt-24 overflow-hidden">
          <Nav />

          <h1 className="text-4xl text-center md:text-6xl text-[#1C665B]">
            {specialist.type}
          </h1>

          <div className="h-full mt-5 overflow-hidden ">
            <div className={`w-full h-full overflow-scroll`}>
              {doctorsArray.map((data) => {
                return (
                  <div
                    className="flex flex-col w-full bg-[#FCFCFC] rounded-lg shadow-lg mb-8"
                    key={data.id}
                  >
                    <div className="flex items-center justify-between w-full p-4">
                      <div className="flex items-center gap-2">
                        <div className="relative w-20 aspect-square">
                          <Image fill src={data.profilePic} alt="ProfilePic" />
                        </div>
                        <div>
                          <h1>{data.name}</h1>
                          <p className="text-sm">{data.type}</p>
                        </div>
                      </div>
                      <Link
                        href={"/"}
                        className="px-3 py-1 text-[#1C665B] border border-[#1C665B] rounded-lg"
                      >
                        Book app.
                      </Link>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export async function getStaticPaths() {
  const paths = specialistsArray.map((specialist) => ({
    params: { category: specialist.id.toString() },
  }));

  return { paths, fallback: false };
}

export async function getStaticProps({ params }) {
  const { category } = params;

  const specialist = specialistsArray.find((spec) => spec.id.toString() === category);

  return {
    props: {
      specialist,
    },
  };
}
