import Head from "next/head";
import Link from "next/link";
import React from "react";

const GetStarted = () => {
  return (
    <>
      <Head>
        <title>Sign-up | NEXTGEN Doctors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="GetStarted">
        <section className="hidden xl:block image-section"></section>
        <form className="w-full xl:w-1/2">
          <section className="rectangle">
            <h2>Let&apos;s Get Started!</h2>

            <label>
              First name
              <input type="text" />
            </label>

            <label>
              Last name
              <input type="text" />
            </label>

            <label>
              Phone no.
              <input type="tel" placeholder="+2348012345678" />
            </label>

            <label>
              Password
              <input type="password" />
            </label>

            <p className="terms">
              Already have an account?&nbsp;
              <Link href={"/login"}>Login</Link>
            </p>

            <p className="terms">
              By continuing, you agree to our&nbsp;
              <span>Terms and conditions</span>
            </p>

            <button type="submit">Continue</button>
          </section>
        </form>
      </div>
    </>
  );
};

export default GetStarted;
