import Head from 'next/head'
import Splash from '@/components/Splash-Screen/Splash'
import Nav from '@/components/Nav'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | NEXTGEN Doctors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Splash />
        <Nav />
      </main>
    </>
  )
}
